// <auto-generated />
using System;
using HelpFinance.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpFinance.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20250913044323_AddTelefone")]
    partial class AddTelefone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HelpFinance.Models.UsuarioModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CRIADO_EM")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CRIADO_EM");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("EMAIL");

                    b.Property<string>("LOGIN")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("LOGIN");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("NOME");

                    b.Property<string>("SENHA")
                        .HasColumnType("longtext")
                        .HasColumnName("SENHA");

                    b.Property<string>("TELEFONE")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TELEFONE");

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
